on:
  release:
    types: [published]
name: Release
env:
  RACK_SDK_VERSION: 1.1.6
jobs:
  buildLinux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build Linux
      uses: ./.github/actions/build_linux
    - name: upload zip
      run: sh ./.github/actions/upload_zip/script.sh ${{ secrets.GITHUB_TOKEN }}
  buildWindows:
    name: Build Windows
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build Windows
      uses: ./.github/actions/build_win
    - name: upload zip
      run: sh ./.github/actions/upload_zip/script.sh ${{ secrets.GITHUB_TOKEN }}
  # buildOsx:
  #   name: Build OSX
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@master
  #   - name: Build OSX
  #     uses: ./.github/actions/build_osx
  #   - name: upload zip
  #     run: sh ./.github/actions/upload_zip/script.sh ${{ secrets.GITHUB_TOKEN }}
